# -*- coding: utf-8 -*-
"""Face_Mask_Detection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yLc0NtsI0UAafTh_-P0Ye8nWVr5ypRsm
"""

!pip install kaggle

"""Importing Face Mask Dataset"""

# API to fetch the dataset from Kaggle
!kaggle datasets download omkargurav/face-mask-dataset

!ls

# extracting the compressed Dataset
from zipfile import ZipFile
dataset='face-mask-dataset.zip'

with ZipFile(dataset,'r') as zip:
  zip.extractall()
  print('The dat')

!ls

"""Importing the Dependencies"""

import os
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.image as mpimg
import cv2
from google.colab.patches import cv2_imshow
from PIL import Image
from sklearn.model_selection import train_test_split